/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_Screen;
import book_management.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeString.search;
/**
 *
 * @author tuan.nguyen1
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        setTitle("Student Management");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        exit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        xemsach = new javax.swing.JMenu();
        Muon = new javax.swing.JMenu();
        returnBook = new javax.swing.JMenu();
        timkiem = new javax.swing.JMenu();
        dangxuat = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("BOOK MANAGEMENT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 390, -1));

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/docsach.jpg"))); // NOI18N
        image1.setText("jLabel3");
        getContentPane().add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 130, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/iconvuive.JPG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 110, 170));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/icontim.JPG"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 60, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/iconlogin.JPG"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 50, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/iconhorror.JPG"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 140, 110));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/iconcomic.JPG"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 140, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/icondoc.JPG"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 60, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/iconsach2.JPG"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/iconbutchi.JPG"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 140, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Screen/nền3.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 560));

        exit.setText("Home");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit ");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        exit.add(jMenuItem1);

        jMenuBar1.add(exit);

        xemsach.setText("Book Information");
        xemsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xemsachMouseClicked(evt);
            }
        });
        jMenuBar1.add(xemsach);

        Muon.setText("Borrow Book");
        Muon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MuonMouseClicked(evt);
            }
        });
        jMenuBar1.add(Muon);

        returnBook.setText("Return Book");
        returnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBookMouseClicked(evt);
            }
        });
        jMenuBar1.add(returnBook);

        timkiem.setText("Search Book");
        timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemMouseClicked(evt);
            }
        });
        jMenuBar1.add(timkiem);

        dangxuat.setText("Describe");
        dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangxuatMouseClicked(evt);
            }
        });
        jMenuBar1.add(dangxuat);

        jMenu1.setText("Log Out");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xemsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xemsachMouseClicked
        
        try { 
            Book_Infor tts = new Book_Infor();
            tts.setVisible(true );
            tts.pack();
            tts.setLocationRelativeTo(null);
            tts.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_xemsachMouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System .exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void dangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangxuatMouseClicked
        
        Describe describe;
        describe = new Describe();
        describe.setVisible(true );
        describe.pack();
        describe.setLocationRelativeTo(null);
        describe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_dangxuatMouseClicked

    private void MuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MuonMouseClicked
       try { 
            Borrow_Book MUON = new Borrow_Book();
            MUON.setVisible(true );
            MUON.pack();
            MUON.setLocationRelativeTo(null);
            MUON.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_MuonMouseClicked

    private void timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemMouseClicked
        SearchBook search;
        try{
            search = new SearchBook();
            search.setVisible(true );
            search.pack();
            search.setLocationRelativeTo(null);
            search.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();  
        }catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_timkiemMouseClicked

    private void returnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookMouseClicked
        Give_Book give;
        try {
            give = new Give_Book();
            give.setVisible(true);
        give.pack();
        give.setLocationRelativeTo(null);
        give.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_returnBookMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure to Log Out ? ", "Log Out", JOptionPane.ERROR_MESSAGE);
        if(a==JOptionPane.YES_OPTION){
            Sign_In sign;
            try {
                sign = new Sign_In();
                sign.setVisible(true);
                sign.setLocationRelativeTo(null);
                this.dispose();
                this.pack();
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Muon;
    private javax.swing.JMenu dangxuat;
    private javax.swing.JMenu exit;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu returnBook;
    private javax.swing.JMenu timkiem;
    private javax.swing.JMenu xemsach;
    // End of variables declaration//GEN-END:variables
}
